package com.zjasm.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SimpleAuthService service = new SimpleAuthService();
 * SimpleAuthServicePortType portType = service.getSimpleAuthServiceHttpPort();
 * portType.getUserSys(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SimpleAuthService", targetNamespace = "http://webservice.api.commnetsoft.com", wsdlLocation = "http://guser.zjzwfw.gov.cn/sso/service/SimpleAuthService?wsdl")
public class SimpleAuthService extends Service {

	private final static URL SIMPLEAUTHSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.zjasm.webservice.SimpleAuthService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.zjasm.webservice.SimpleAuthService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://guser.zjzwfw.gov.cn/sso/service/SimpleAuthService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://guser.zjzwfw.gov.cn/sso/service/SimpleAuthService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SIMPLEAUTHSERVICE_WSDL_LOCATION = url;
	}

	public SimpleAuthService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SimpleAuthService() {
		super(SIMPLEAUTHSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.api.commnetsoft.com", "SimpleAuthService"));
	}

	/**
	 * 
	 * @return returns SimpleAuthServicePortType
	 */
	@WebEndpoint(name = "SimpleAuthServiceHttpPort")
	public SimpleAuthServicePortType getSimpleAuthServiceHttpPort() {
		return super.getPort(new QName("http://webservice.api.commnetsoft.com",
				"SimpleAuthServiceHttpPort"), SimpleAuthServicePortType.class);
	}

}
